# config.yml
# validate with pydantic
metadata:
  version: 1.0
  env: "dev"

data_generator:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  ticker_initial_prices:
    GME: 150.0
    BYND: 200.0
    BP: 15.0

data_processor:
  missing_data_handler:
    strategy: "forward_fill"  # options: drop, forward_fill
  make_stationarity:
    method: "difference"  # options: difference, log
  test_stationarity:
    method: "ADF"
    p_value_threshold: 0.05  # Significance level: p-value below this means the series is stationary
  scaler:
    method: "minmax"  # options: standardize, minmax

stats_model:
  ARIMA:
    run: True
    parameters_fit:
      p: 2
      d: 1
      q: 4
    parameters_predict:
      steps: 3
  GARCH:
    run: True
    parameters_fit:
      p: 1
      q: 1
      dist: "t"  # options: normal, t

