# config.dev.yml
# validate with pydantic
data_generator:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  ticker_initial_prices:
    GME: 150.0
    BYND: 200.0
    BP: 15.0
data_processor:
  missing_data_handler:
    strategy: "forward_fill"  # options: drop, forward_fill
  stationarity_processor:
    p_value_threshold: 0.05
  scaler:
    method: "minmax"  # options: standardize, minmax
  
