# validate with pydantic
data_generator:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  ticker_initial_prices:
    GME: 150.0
    BYND: 200.0
    BP: 15.0
data_processor:
  missing_data_handler:
    interpolation_method: "linear"
    strategy: "forward_fill"  # Options: drop, forward_fill, fill_mean, fill_mode, interpolate
  stationarity_processor:
    p_value_threshold: 0.05
    default_column: "price"
  scaler:
    method: "minmax"  # Options: standardize, minmax, pct_change, log
    columns: ["price", "volume"]
    minmax_range: [0, 1]  # For MinMax scaling
