# yml schema to validate against config.yml

metadata:
  description: "time series forecasting configuration"
  version: { type: float, required: true }
  environment: { type: str, required: true, enum: ["dev", "test", "prod"] }

data_generator:
  description: "generate time series data"
  start_date: { type: str, required: true, pattern: "^\d{4}-\d{2}-\d{2}$" }
  end_date: { type: str, required: true, pattern: "^\d{4}-\d{2}-\d{2}$" }
  anchor_prices: { type: map, required: true, values: float }  # Ticker prices

data_processor:
  description: "preprocess time series data"
  handle_missing_values: { strategy: { type: str, enum: ["drop", "forward_fill"] } }
  make_stationary: { method: { type: str, enum: ["difference", "log"] } }
  test_stationarity:
    method: { type: str, enum: ["ADF"] }
    p_value_threshold: { type: float, min: 0.0, max: 1.0 }
  scaling: { method: { type: str, enum: ["standardize", "minmax"] } }

stats_model:
  description: "stats models for time series forecasting"
  ARIMA:
    description: "autoregressive integrated moving average parameters"
    enabled: { type: bool }
    parameters_fit: { p: int, d: int, q: int }
    parameters_predict_steps: { type: int }
  GARCH:
    description: "generalized autoRegressive conditional heteroskedasticity parameters"
    enabled: { type: bool }
    parameters_fit: { p: int, q: int, dist: { type: str, enum: ["normal", "t"] } }
    parameters_predict_steps: { type: int }
